# Site settings
title: GBR博客
SEOTitle: GBR博客
header-img: img/index.jpg
email: 3552526022@qq.com
description: "Wellcom To My blog"
keyword: "gbr, GBR Blog, 龚邦睿, 龚邦睿的博客, gongbangrui"
url: "http://gongbangrui.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/gongbangrui/gongbangrui.github.io" # you code repository
home_repo: "https://ce17877258.icoc.bz  "

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "gbr"
sidebar-avatar: /img/about-Otone.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     _GBR
#zhihu_username:     
github_username:    gongbangrui
#facebook_username: 
jianshu_username:  没有
twitter_username:   没有




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: gongbangrui

# Gitalk
#gitalk:
#  enable: true    #是否开启Gitalk评论
#  clientID: 55ee13bda0964ed5c2ec                           #生成的clientID
#  clientSecret: 28445a559ed2ac0cc42cf616dd4fc77b8d8c4223   #生成的clientSecret
#  repo: gongbangrui.github.io    #仓库名称
#  owner: 'gongbangrui'   #github用户名
#  admin: ['gongbangrui']
#  distractionFreeMode: true #是否启用类似FB的阴影遮罩


<!-- Gitalk 评论 start  -->
{% if site.gitalk.enable %}
<!-- Link Gitalk 的支持文件  -->
<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script src="https://unpkg.com/gitalk@latest/dist/gitalk.min.js"></script>

<div id="gitalk-container"></div>
    <script type="text/javascript">
    var gitalk = new Gitalk({

    // gitalk的主要参数
        clientID: `55ee13bda0964ed5c2ec`,
        clientSecret: `28445a559ed2ac0cc42cf616dd4fc77b8d8c4223`,
        repo: `gongbangrui.github.io`,
        owner: 'gongbangrui',
        admin: ['gongbangrui'],
    
    });
    gitalk.render('gitalk-container');
</script>
{% endif %}
<!-- Gitalk end -->


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-124497414-1'            # Format: UA-xxxxxx-xx
ga_domain: auto             # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0             # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# links
links: [
    {
        title: "个人のGitHub",
        href: "https://github.com/gongbangrui	"
    }
]
